#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
#
# Generate compile_commands.json for kvmtool, inspired by the Linux kernel's
# scripts/clang-tools/gen_compile_commands.py.
#
# This script parses .cmd files generated by the kvmtool Makefile during
# compilation and produces a compile_commands.json file that can be used by
# clangd and other LSP-based tools for code navigation, completion, and
# diagnostics.
#
# Usage:
#   1. Build the project first:  make
#   2. Generate the index:        make compile_commands
#      Or directly:               python3 scripts/gen_compile_commands.py
#
# The .cmd files are located alongside the .o files and contain lines in the
# format:
#   cmd_<output> := <compiler> <flags> <source> -o <output>

import argparse
import json
import os
import re
import sys


def parse_cmdfile(path, root_path):
    """Parse a .cmd file and return (directory, command, output, source).

    Each .cmd file contains lines like:
        cmd_<output_path> := <full_compile_command>

    The directory is always the project root, since the source paths in the
    .cmd files are relative to where make was invoked (the project root).
    """
    with open(path, 'r') as f:
        for line in f:
            line = line.rstrip()
            match = re.match(r'cmd_(\S+)\s*:=\s*(.+)', line)
            if match:
                output = match.group(1)
                command = match.group(2)
                # Extract the source file from the command line.
                # The source file is the argument just before -o.
                # Command format: <cc> -c <flags> <source.c> -o <output.o>
                parts = command.split()
                source = None
                for i, part in enumerate(parts):
                    if part == '-o' and i + 1 < len(parts):
                        # Source is the argument before -o
                        if i > 0:
                            source = parts[i - 1]
                        break

                # The directory is always the project root because
                # make is invoked from the project root and all paths
                # in .cmd files are relative to it.
                directory = root_path

                return directory, command, output, source

    return None


def find_cmdfiles(root_path):
    """Find all .cmd files under the given root path."""
    cmdfiles = []
    for dirpath, dirnames, filenames in os.walk(root_path):
        for filename in filenames:
            if filename.endswith('.cmd'):
                cmdfiles.append(os.path.join(dirpath, filename))
    return cmdfiles


def main():
    parser = argparse.ArgumentParser(
        description='Generate compile_commands.json for kvmtool from .cmd files.')
    parser.add_argument('-o', '--output', default='compile_commands.json',
                        help='Output file path (default: compile_commands.json)')
    parser.add_argument('-s', '--source-only', action='store_true',
                        help='Only include entries where the source file exists')
    parser.add_argument('paths', nargs='*',
                        help='Directories to search for .cmd files (default: .)')
    args = parser.parse_args()

    root_path = args.paths[0] if args.paths else '.'
    root_path = os.path.abspath(root_path)

    cmdfiles = find_cmdfiles(root_path)
    if not cmdfiles:
        print('WARNING: No .cmd files found. Did you run "make" first?',
              file=sys.stderr)
        sys.exit(1)

    compile_commands = []
    for cmdfile in sorted(cmdfiles):
        result = parse_cmdfile(cmdfile, root_path)
        if result is None:
            continue

        directory, command, output, source = result

        if source is None:
            continue

        # Resolve source file path relative to the project root
        # If source is a relative path, make it relative to directory
        if not os.path.isabs(source):
            source_abs = os.path.normpath(os.path.join(directory, source))
        else:
            source_abs = os.path.normpath(source)

        # Optionally verify source exists
        if args.source_only and not os.path.isfile(source_abs):
            continue

        entry = {
            'directory': directory,
            'command': command,
            'file': source_abs,
        }
        compile_commands.append(entry)

    # De-duplicate: prefer non-static .o entries when both exist for the same source
    seen_sources = {}
    deduped = []
    for entry in compile_commands:
        source = entry['file']
        is_static = '.static.o' in entry.get('command', '')
        if source not in seen_sources:
            seen_sources[source] = (entry, is_static)
        else:
            # Prefer non-static over static for the same source file
            prev_entry, prev_static = seen_sources[source]
            if prev_static and not is_static:
                seen_sources[source] = (entry, is_static)

    deduped = [v[0] for v in seen_sources.values()]
    # Sort by file path for deterministic output
    deduped.sort(key=lambda e: e['file'])

    with open(args.output, 'w') as f:
        json.dump(deduped, f, indent=2)

    print(f'Generated {args.output} with {len(deduped)} entries')


if __name__ == '__main__':
    main()

